# .github/workflows/reusable-release-pipeline.yml

name: Terraform Release Pipeline

on:
  workflow_call:
    inputs:
      version_type:
        required: true
        type: string  # patch, minor, or major

jobs:
  versioning_and_release:
    name: Versioning and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "Aravind Koniki"
          git config --global user.email "aravind_koniki@hotmail.com"

      - name: Bump Version
        id: bump_version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          new_version=$(npm version ${{ inputs.version_type }})
          echo "::set-output name=new_version::$new_version"

      - name: Commit Version Bump
        run: |
          git commit -am "Bump version to ${{ steps.bump_version.outputs.new_version }}"
          git tag ${{ steps.bump_version.outputs.new_version }}

      - name: Push New Tag
        run: |
          git push origin --tags
